#!/bin/bash

# Treat unset variables as an error when performing parameter expansion
# and exit immediately if a simple command exits with a non-zero status.
# Returns the exit value of the last (rightmost) command to exit with
# non-zero in a pipeline of commands.
set -u

# This script shuts down apache2 httpd in an orderly fashion. See http://smarden.org/runit/runsv.8.html

# Some notes on bash scripting:
# Variables flagged as local readonly will not terminate the script if they are set by command substitution.

#echo "Shutdown tomcat9"
#(echo SHUTDOWN | /usr/bin/nc localhost 8180 &)

if [ -r $HOME/var/run/apache2/apache2.pid ] ; then
    echo "Shutdown apache2"
    kill -WINCH $(cat $HOME/var/run/apache2/apache2.pid)
fi
